/*
    Shubh Khandelwal
*/

#pragma once
#include <stdexcept>
#include <vector>

namespace fitpack
{
    extern "C"
    {

        void curfit_(
            int* iopt, int* m, double* x, double* y, double* w, 
            double* xb, double* xe, int* k, double* s, int* nest,
            int* n, double* t, double* c, double* fp, 
            double* wrk, int* lwrk, int* iwrk, int* ier
        );

        void spalde_(
            double* t, int* n, double* c, int* k1, 
            double* x, double* d, int* ier
        );

        void splev_(
            double* t, int* n, double* c, int* k, 
            double* x, double* y, int* m, int* ier
        );

    }
}

namespace splplanner
{

    struct Spline
    {
        std::vector<double> knots;
        std::vector<double> coeffs;
        int degree;
        int num_knots;
    };

    /**
     * @brief Fits a smoothing B-spline to the given data.
     * 
     * @param x Independent variable array (must be strictly increasing).
     * @param y Dependent variable array (y = f(x)).
     * @param s Smoothing factor (e.g., 0.005).
     * @param k Degree of the spline (default is 3 for cubic).
     * 
     * @return Spline object containing knots and coefficients.
     */
    inline Spline splrep(const std::vector<double>& x, const std::vector<double>& y, double s, int k = 3)
    {

        // curfit_ parameters
        int iopt = 0; // 0 = standard smoothing, 1 = use provided knots
        int m = x.size();
        std::vector<double> w(m, 1.0);
        double xb = x.front();
        double xe = x.back();
        int nest = m + k + 1;
        int n = 0; // Number of knots
        std::vector<double> t(nest);
        std::vector<double> c(nest);
        double fp = 0.0;
        int lwrk = m * (k + 1) + nest * (7 + 3 * k);
        std::vector<double> wrk(lwrk);
        std::vector<int> iwrk(nest);
        int ier = 0;

        fitpack::curfit_(
            &iopt, &m, const_cast<double*>(x.data()), const_cast<double*>(y.data()), w.data(),
            &xb, &xe, &k, &s, &nest, 
            &n, t.data(), c.data(), &fp, 
            wrk.data(), &lwrk, iwrk.data(), &ier
        );

        if (ier > 0)
        {
            throw std::runtime_error("FITPACK curfit failed with error code: " + std::to_string(ier));
        }

        t.resize(n);
        c.resize(n);

        return {t, c, k, n};

    }

    /**
     * @brief Evaluates a B-spline or its derivatives at a specific point.
     * @param spline The Spline object generated by splrep.
     * @param u The point at which to evaluate the spline.
     * @param der The order of the derivative to compute (default = 0).
     * @return The interpolated value or derivative.
     */
    inline double splev(const Spline& spline, double u, int der = 0)
    {

        if (der < 0) throw std::invalid_argument("Derivative order cannot be negative.");
        if (der > spline.degree) return 0.0;

        int ier = 0;

        if (der == 0) 
        {

            // splev_ parameters
            int n = spline.num_knots;
            int k = spline.degree;
            int m = 1;
            double result = 0.0;

            fitpack::splev_(
                const_cast<double*>(spline.knots.data()), &n, const_cast<double*>(spline.coeffs.data()), &k,
                &u, &result, &m, &ier
            );

            if (ier > 0) throw std::runtime_error("FITPACK splev failed: " + std::to_string(ier));
            return result;
        
        } else 
        {

            // splade_ parameters
            int n = spline.num_knots;
            int k1 = spline.degree + 1;
            std::vector<double> d(k1, 0.0);

            fitpack::spalde_(
                const_cast<double*>(spline.knots.data()), &n, const_cast<double*>(spline.coeffs.data()), &k1,
                &u, d.data(), &ier
            );

            if (ier > 0) throw std::runtime_error("FITPACK spalde failed: " + std::to_string(ier));
            return d[der];
        
        }

    }

}