/*
    Shubh Khandelwal
*/

#pragma once
#include <stdexcept>
#include <vector>

namespace fitpack
{
    extern "C"
    {

        void curfit_(
            int* iopt, int* m, double* x, double* y, double* w, 
            double* xb, double* xe, int* k, double* s, int* nest,
            int* n, double* t, double* c, double* fp, 
            double* wrk, int* lwrk, int* iwrk, int* ier
        );

        void spalde_(
            double* t, int* n, double* c, int* k1, 
            double* x, double* d, int* ier
        );

        void splev_(
            double* t, int* n, double* c, int* k, 
            double* x, double* y, int* m, int* ier
        );

    }
}

namespace splplanner
{

    struct Spline
    {
        std::vector<double> knots;
        std::vector<double> coeffs;
        int degree;
        int num_knots;
    };

    /**
     * @brief Fits a smoothing B-spline to the given data.
     * @param u Independent variable array (must be strictly increasing).
     * @param x Dependent variable array.
     * @param s Smoothing factor (e.g., 0.005).
     * @param k Degree of the spline (default is 3 for cubic).
     * @return Spline object containing knots and coefficients.
     */
    inline Spline splrep(const std::vector<double>& u, const std::vector<double>& x, double s, int k = 3)
    {

        if (u.size() != x.size() || u.empty())
        {
            throw std::invalid_argument("Input vectors must be of the same non-zero size.");
        }

        int m = u.size();
        int iopt = 0; // 0 = standard smoothing, 1 = use provided knots
        std::vector<double> w(m, 1.0); // Weights
        
        double xb = u.front();
        double xe = u.back();
        
        // nest is the maximum number of knots (overestimate is safe)
        int nest = m + k + 1;
        
        int num_knots = 0;
        std::vector<double> knots(nest);
        std::vector<double> coeffs(nest);
        double fp = 0.0; // Sum of squared residuals
        
        // Fortran memory workspace calculations
        int lwrk = m * (k + 1) + nest * (7 + 3 * k);
        std::vector<double> wrk(lwrk);
        std::vector<int> iwrk(nest);
        int ier = 0;

        // Note: const_cast is used because Fortran bindings don't support 'const', 
        // but curfit_ does not mutate the input 'u' and 'x' arrays.
        fitpack::curfit_(
            &iopt, &m, const_cast<double*>(u.data()), const_cast<double*>(x.data()), w.data(),
            &xb, &xe, &k, &s, &nest, 
            &num_knots, knots.data(), coeffs.data(), &fp, 
            wrk.data(), &lwrk, iwrk.data(), &ier
        );

        if (ier > 0)
        {
            // ier == 10 is often just a warning that tolerance wasn't perfectly met
            // but the spline is still usable. Others are fatal.
            if (ier != 10)
            {
                throw std::runtime_error("FITPACK curfit failed with error code: " + std::to_string(ier));
            }
        }

        // Shrink vectors to the actual number of knots used
        knots.resize(num_knots);
        coeffs.resize(num_knots);

        return {knots, coeffs, k, num_knots};
    }

    /**
     * @brief Evaluates a B-spline or its derivatives at a specific point.
     * @param spline The Spline object generated by splrep.
     * @param u_val The point at which to evaluate the spline.
     * @param der The order of the derivative to compute (default = 0).
     * @return The interpolated value or derivative.
     */
    inline double splev(const Spline& spline, double u_val, int der = 0)
    {

        if (der < 0) throw std::invalid_argument("Derivative order cannot be negative.");
        if (der > spline.degree) return 0.0;

        int ier = 0;

        if (der == 0) 
        {

            int m = 1; 
            double result = 0.0;
            int n = spline.num_knots;
            int k = spline.degree;

            fitpack::splev_(
                const_cast<double*>(spline.knots.data()), &n, const_cast<double*>(spline.coeffs.data()), &k,
                &u_val, &result, &m, &ier
            );

            if (ier > 0) throw std::runtime_error("FITPACK splev failed: " + std::to_string(ier));
            return result;
        
        } else 
        {

            int n = spline.num_knots;
            int k1 = spline.degree + 1;
            
            // Array to hold derivatives: d[0]=pos, d[1]=vel, d[2]=acc, d[3]=jerk
            std::vector<double> d(k1, 0.0);

            fitpack::spalde_(
                const_cast<double*>(spline.knots.data()), &n, const_cast<double*>(spline.coeffs.data()), &k1,
                &u_val, d.data(), &ier
            );

            if (ier > 0) throw std::runtime_error("FITPACK spalde failed: " + std::to_string(ier));
            return d[der];
        
        }

    }

}